import { Hero } from "./hero";

export const HEROES : Hero[] = [
    { id: 1, name: 'Tony Stark - Ironman' },
    { id: 2, name: 'Steve Rogers - Captain America' },
    { id: 3, name: 'Thor - God of Thunder' },
    { id: 4, name: 'Carol Danvers - Captain Marvel' },
    { id: 5, name: 'Bruce Banner - Hulk' },
    { id: 6, name: 'Scott Lang - Antman' },    
    { id: 7, name: 'Dr. Stephen Strange - Dr. Strange' },
    { id: 8, name: 'T-Challa - Black Panther' },
    { id: 9, name: 'Natasha - Black Widow' },    
    { id: 10, name: 'Clinton Barton - Hawkaye' },    
    { id: 11, name: 'Peter Parker - Spiderman' },
    { id: 12, name: 'Loki - God of Mischief' },
    { id: 13, name: 'Peter Quill - Star Lord' },
    { id: 14, name: 'Rocket Raccoon - Rabbit' },
    { id: 15, name: 'Groot - I am Groot' },
    { id: 16, name: 'Scarlet Witch - Wanda' },
    { id: 17, name: 'Nebula' },
    { id: 18, name: 'Gamora' },
    { id: 19, name: 'Drax' },
    { id: 20, name: 'James Rhoes - War Machine' },
    { id: 21, name: 'Nick Fury' },
    { id: 22, name: 'Vision - Altron' },
]